name: Discord Webhook

on:
  push:
    branches:
      - main  # Change this to your branch

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "**New update pushed to GitHub!** 🚀\nCommit: '${{ github.event.head_commit.message }}'\nBy: '${{ github.event.pusher.name }}'"}' \
          https://discord.com/api/webhooks/1340050981718851645/htNTE-cOmelwfm__4iurxKnu3UtgB7Zt5pSIdyfPWSLCEAq6U9ZZ4ZG878tQ28GwB1Bi
